### ISSUE TITLE
XDG specs have path relative to $HOME and not ~

### ISSUE THREAD

**Issue by carandraug** [srstevenson/xdg#1]
The xdg specification has the default paths relative to `$HOME`. However, this module uses `os.path.expanduser` with a tilde which in the case of windows checks for alternatives to `$HOME`.

**Comment by srstevenson** [comment]
This module [only supports Unix](https://github.com/srstevenson/xdg/blob/1e11573329458306ca3918074784960aa8666fd1/setup.py#L33) as the specification is Unix-centric (for example, it specifies the Unix access modes that `$XDG_RUNTIME_DIR` should have, and uses Unix path separators). However, you're completely right that it refers to `$HOME` rather than `~`, so I've released [1.0.4](https://github.com/srstevenson/xdg/releases/tag/1.0.4) which now does the same. Thanks for reporting this!
