### ISSUE TITLE
Nameclash with other xdg library

### ISSUE THREAD

**Issue by sphh** [srstevenson/xdg#75]
This library installs into the same directory as `pyxdg` (https://pypi.org/project/pyxdg/ (and https://gitlab.freedesktop.org/xdg/pyxdg/).

There are many situations, when this can become a problem. Some are:
- One package requests `pyxdg` and the other `xdg`. If installed with `pip`, the later overwrites the `xdg/__init__.py` file.
- Having installed both and uninstalling one of it, the `xdg/__init__.py` file is removed (making other packages throwing an error, e.g. https://github.com/spyder-ide/spyder/issues/16448)

It would be great, if either:
- both packages can cohabit in the same installation, or at least
- a warning is issued, that those packages are incompatible

A change of installation directory was declined (https://github.com/srstevenson/xdg/issues/35), suggesting that `pyxdg` should install into the `pyxdg` directory. (See also https://github.com/srstevenson/xdg/issues/10.)

There is also the suggestion of https://gitlab.freedesktop.org/xdg/pyxdg/-/issues/19.

Unfortunately we (as users) are in the situation, where one package (the first kid on the block) installs into a different directory than its name suggests, which probably led the `xdg` to use the same directory (and claiming, that the other should rename the directory). Would it be possible that you and the [maintainer of `pyxdg`](https://gitlab.freedesktop.org/xdg) put your heads together to find a solution? Thanks, that would be really, really great!

PS: The corresponding bug report for `xdg` is here: https://gitlab.freedesktop.org/xdg/pyxdg/-/issues/24

**Comment by srstevenson** [comment]
I've been thinking again about how to resolve this, which is obviously a pain for the users and maintainers of both packages. I met @takluyver, the pyxdg maintainer, in person at a previous PyCon UK, and have no doubt we'd both be willing to implement a solution that fixes the namespace collision whilst avoiding breakage for users of both packages, if such a solution can be found.

Unfortunately, the impasse exists because no such solution has yet been identified. Approaches that have been suggested all break backward compatibility for existing xdg or pyxdg users in some way:

- **Approach**: pyxdg changes namespace to `pyxdg`
  - ✔️ pyxdg no longer collides with xdg in the `xdg` namespace
  - ❌ pyxdg users' code is broken if previous pyxdg releases are yanked from PyPI
  - ❌ if previous pyxdg releases are not yanked from PyPI, the namespace collision remains
- **Approach**: xdg changes namespace to `xdg_base_directory` or similar
  - ✔️ xdg no longer collides with pyxdg in the `xdg` namespace
  - ❌ xdg users' code is broken if previous xdg releases are yanked from PyPI
  - ❌ if previous xdg releases are not yanked from PyPI, the namespace collision remains
- **Approach**: merge xdg and pyxdg into a single package whose API is the union of the two original packages in the `xdg` namespace. pyxdg becomes an empty package that just depends on xdg, or xdg becomes an empty package that just depends on pyxdg.
  - ✔️ pyxdg and xdg no longer collide in the `xdg` namespace
  - ✔️ users of both packages have a update path that maintains backward compatibility (except for Python 2.7 support, see below)
  - ❌ pyxdg's code is LGPL licensed, which means some previous users of xdg would not be able to use the unified package ([reference](https://github.com/srstevenson/xdg/issues/83#issuecomment-1039311015))
  - ❌ Python 2.7 support is lost (which `pyxdg` currently has), as `xdg`'s public API uses Python 3 features such as the `pathlib` module. While there is a backport of `pathlib` to earlier Python versions, this has dropped support for Python 2.7.

Is there a solution that's not been discussed so far, that'll let us move past the impasse without breaking application code for users of either package?

**Comment by not-my-profile** [comment]
There is another aspect that hasn't been mentioned here yet: `pyxdg` is [packaged for many Linux distributions](https://repology.org/project/python:pyxdg/versions). Contrary to PyPI packages Linux packages generally cannot simply be yanked.

Fun sidenote: if you have `python3-xdg` installed on Debian then `pip install xdg` fails:

```
$ pip install xdg                           
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: xdg in /usr/lib/python3/dist-packages (5)
```

(which is an incredibly confusing error message ... I just opened pypa/pip/issues/11695 about that)

> Is there a solution that's not been discussed so far, that'll let us move past the impasse without breaking application code for users of either package?

Yes: change the name of your package without yanking prior versions and bump the major version of the package.

**Comment by not-my-profile** [comment]
No because as Scott mentioned this library is licensed under ISC whereas pyxdg is licensed under the LGPL.
Apparently Debian already did something like that the reason for the PIP output I mentioned earlier isn't a bug in pip but the fact that the Debian maintainers have merged both libraries into one Debian package.

**Comment by sphh** [comment]
What I meant is not to use the existing code of `[py]xdg`, but to recreate that API with the help of `xdg[_base_directory]`. As I understand it, the API is not licensed, it is the implementation which falls under the LGPL. But I might be wrong here …

**Comment by not-my-profile** [comment]
Ah yes a clean room implementation would probably be legal ... but I don't really think anybody cares enough about this to do it ... besides this wouldn't really work cleanly when the pyxdg API is updated.

**Comment by takluyver** [comment]
I think it's unlikely that pyxdg will get any significant API changes - it's barely changed for many years. However, it's also a much bigger API surface than this package. This one covers only the XDG base directory spec, whereas PyXDG tries to cover several different XDG specs (using fewer, bigger packages was more attractive back when Python packaging tools were worse).

So if someone really wanted to, grafting the API of the xdg package onto PyXDG is probably simpler - there's a lot less to bring over, and no need for a clean-room implementation, since the ISC licensed code can be used in an LGPL work. But the xdg package would also have to change to solve the name clash, and it's not a priority for me.

**Comment by sphh** [comment]
> So if someone really wanted to, grafting the API of the xdg package onto PyXDG is probably simpler

There is already a patch in Debian to bring `xdg[_base_directory]`'s API to `[py]xdg`: https://salsa.debian.org/python-team/packages/pyxdg/-/commit/2e61e056826ea13e6a1a49202a33213f6ee38219 (@not-my-profile's bug reports unearthed that patch).

But there is still the licence issue: https://github.com/srstevenson/xdg/issues/75#issuecomment-1370747992 and https://github.com/srstevenson/xdg/issues/83#issuecomment-1039311015, hence some people will not like this approach. To satisfy these users `[py]xdg`'s API has to be reimplemented in `xdg` (this package).

This approach would need:
1. Re-implement all xdg specifications in `xdg` (this package).
2. Write a wrapper for `[py]xdg`'s API.

@srstevenson: Would you be happy to take the burden of maintaining such a package? I myself could imagine to do some PR …

**Comment by srstevenson** [comment]
Yes, I'd be willing to maintain a merged package containing the union of the two APIs. If the pyxdg API is clean-room implemented in xdg then it looks like we have a resolution that works, including for users who can't use LGPL licensed code. Current pyxdg users would lose Python 2.7 support, but given Python 2.7 has been EOL for three years that seems like a reasonable compromise.

**Comment by takluyver** [comment]
A clean-room implementation is likely to be a lot of effort for relatively little gain - I suspect large parts of PyXDG don't have many users, and I think relatively few people really can't use LGPL code. I'm not saying they don't exist or should be ignored, just that I don't think there's all that many of them. PySide is LGPL licensed, for instance, and a big reason people use that is to avoid licensing headaches with PyQt.

Of course I'm not going to stop anyone if that's the route you want to go down, but I might suggest an alternative which is less work: release this package with a different import name (e.g. `xdg_base_dirs`) for the people who can't accept LGPL, and combine the two `xdg` APIs in PyXDG (i.e. LGPL licensed) to avoid the name clash, with no clean-room requirement.

**Comment by srstevenson** [comment]
I've opened a PR to PyXDG at https://github.com/takluyver/pyxdg/pull/19 to add the xdg API there, and renamed xdg to xdg-base-dirs. Hopefully this is a satisfactory resolution to the collision.
